config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/athenarc/EOSCF-ContentBasedRS:
      branch: master
      repo: https://github.com/athenarc/EOSCF-ContentBasedRS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-dandelion-maltese.sh
        container: qc.acc_tasty-lime-newfoundland
  QC.Doc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-orchid-llama.sh
        container: qc.doc_snazzy-khaki-kudu
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-ecru-turkey.sh
        container: qc.doc_squirrely-xanthic-discus
      github.com/athenarc/EOSCF-ContentBasedRS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-smalt-tarantula.sh
        container: qc.doc_gamy-ecru-hyrax
  QC.Lic:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-myrtle-seahorse.sh
        container: qc.lic_frumpy-blue-wombat
  QC.Sec:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-jade-squirrel.sh
        container: qc.sec_queasy-wisteria-eagle
  QC.Sty:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-razzmatazz-cheetah.sh
        container: qc.sty_greasy-cinnamon-magpie
      github.com/athenarc/EOSCF-ContentBasedRS hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-smalt-ferret.sh
        container: qc.sty_dorky-cardinal-dog
  QC.Ver:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-flax-bobcat.sh
        container: qc.ver_flabby-thistle-echidna
timeout: 5400
