config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/athenarc/EOSCF-ContentBasedRS:
      branch: master
      repo: https://github.com/athenarc/EOSCF-ContentBasedRS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-ochre-uguisu.sh
        container: qc.acc_stealthy-chartreuse-guppy
  QC.Doc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-smalt-foxhound.sh
        container: qc.doc_zippy-coral-opossum
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-lilac-mastiff.sh
        container: qc.doc_stuffy-orchid-mouse
      github.com/athenarc/EOSCF-ContentBasedRS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-beige-magpie.sh
        container: qc.doc_hasty-white-saola
  QC.Lic:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-asparagus-avocet.sh
        container: qc.lic_messy-cyan-horse
  QC.Sec:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS bandit:
        commands:
        - /usr/bin/env sh .sqa/script.messy-salmon-goose.sh
        container: qc.sec_lousy-persimmon-axolotl
  QC.Sty:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-lime-chameleon.sh
        container: qc.sty_flabby-puce-bracke
      github.com/athenarc/EOSCF-ContentBasedRS hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-aquamarine-flounder.sh
        container: qc.sty_woozy-rust-dhole
  QC.Ver:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-cream-terrier.sh
        container: qc.ver_craggy-plum-otter
timeout: 5400
