config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/athenarc/EOSCF-ContentBasedRS:
      branch: master
      repo: https://github.com/athenarc/EOSCF-ContentBasedRS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-alizarin-hedgehog.sh
        container: qc.acc_silly-pear-hyena
  QC.Doc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-lemon-bombay.sh
        container: qc.doc_baggy-alizarin-javanese
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-champagne-hamster.sh
        container: qc.doc_nippy-tomato-drever
      github.com/athenarc/EOSCF-ContentBasedRS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-silver-birman.sh
        container: qc.doc_wiggy-cerise-salamander
  QC.Lic:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-amber-russel.sh
        container: qc.lic_cranky-peach-spaniel
  QC.Met:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-lime-civet.sh
        container: qc.met_cheeky-salmon-beetle
  QC.Sec:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-vermilion-kangaroo.sh
        container: qc.sec_nippy-rust-molly
  QC.Sty:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-olivine-tang.sh
        container: qc.sty_scanty-beige-seal
      github.com/athenarc/EOSCF-ContentBasedRS jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cerise-wasp.sh
        container: qc.sty_skanky-orange-devil
  QC.Ver:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-taupe-nightingale.sh
        container: qc.ver_skanky-gold-shark
timeout: 5400
