config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/athenarc/EOSCF-ContentBasedRS:
      branch: master
      repo: https://github.com/athenarc/EOSCF-ContentBasedRS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-zucchini-barracuda.sh
        container: qc.acc_shaky-puce-numbat
  QC.Doc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-cobalt-dog.sh
        container: qc.doc_cheeky-cerulean-catfish
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-crimson-skunk.sh
        container: qc.doc_slimy-ultramarine-sparrow
      github.com/athenarc/EOSCF-ContentBasedRS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-carmine-beaver.sh
        container: qc.doc_clammy-cardinal-chinook
  QC.Lic:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-taupe-vulture.sh
        container: qc.lic_foggy-copper-kangaroo
  QC.Sec:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS bandit:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-harlequin-saola.sh
        container: qc.sec_ready-blue-panda
  QC.Sty:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-maroon-lemming.sh
        container: qc.sty_flimsy-charcoal-caracal
      github.com/athenarc/EOSCF-ContentBasedRS hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-purple-fish.sh
        container: qc.sty_lovely-wheat-collie
  QC.Ver:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-cinnamon-chameleon.sh
        container: qc.ver_cozy-pink-cheetah
timeout: 5400
