config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/athenarc/EOSCF-ContentBasedRS:
      branch: master
      repo: https://github.com/athenarc/EOSCF-ContentBasedRS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-apricot-abyssinian.sh
        container: qc.acc_paltry-saffron-drever
  QC.Doc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-dandelion-monster.sh
        container: qc.doc_zippy-mauve-bison
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-sangria-spoonbill.sh
        container: qc.doc_muzzy-rust-tarsier
      github.com/athenarc/EOSCF-ContentBasedRS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-wisteria-guppy.sh
        container: qc.doc_randy-wisteria-cuscus
  QC.Lic:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-indigo-rabbit.sh
        container: qc.lic_skinny-amber-bullfrog
  QC.Sec:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-periwinkle-gar.sh
        container: qc.sec_flaky-fuchsia-gecko
  QC.Sty:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-white-dog.sh
        container: qc.sty_homey-dandelion-sloth
      github.com/athenarc/EOSCF-ContentBasedRS hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-saffron-penguin.sh
        container: qc.sty_flimsy-red-cattle
  QC.Ver:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-salmon-bear.sh
        container: qc.ver_sleazy-mauve-scorpion
timeout: 5400
