config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/athenarc/EOSCF-ContentBasedRS:
      branch: master
      repo: https://github.com/athenarc/EOSCF-ContentBasedRS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-red-dog.sh
        container: qc.acc_leaky-orange-mongrel
  QC.Doc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-coral-urchin.sh
        container: qc.doc_seedy-cerise-seal
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-firebrick-moose.sh
        container: qc.doc_snappy-fuchsia-boar
      github.com/athenarc/EOSCF-ContentBasedRS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-blue-sheep.sh
        container: qc.doc_droopy-platinum-butterfly
  QC.Lic:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-magnolia-warthog.sh
        container: qc.lic_jumpy-amber-barracuda
  QC.Met:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-pink-burmese.sh
        container: qc.met_sleazy-cinnamon-bombay
  QC.Sec:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-indigo-vulture.sh
        container: qc.sec_sleepy-purple-kakapo
  QC.Sty:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-sapphire-pinscher.sh
        container: qc.sty_cozy-gamboge-schnauzer
      github.com/athenarc/EOSCF-ContentBasedRS jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-black-elephant.sh
        container: qc.sty_trippy-cerulean-frog
  QC.Ver:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-crimson-sparrow.sh
        container: qc.ver_sloppy-smalt-butterfly
timeout: 5400
