config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/athenarc/EOSCF-ContentBasedRS:
      branch: master
      repo: https://github.com/athenarc/EOSCF-ContentBasedRS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cinnamon-gibbon.sh
        container: qc.acc_seedy-chartreuse-mist
  QC.Doc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-linen-buzzard.sh
        container: qc.doc_foggy-goldenrod-beaver
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-azure-bird.sh
        container: qc.doc_whiny-periwinkle-lionfish
      github.com/athenarc/EOSCF-ContentBasedRS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-lavender-dodo.sh
        container: qc.doc_cheeky-alizarin-lizard
  QC.Lic:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-beige-labradoodle.sh
        container: qc.lic_squirrely-razzmatazz-monkey
  QC.Sec:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-bronze-angelfish.sh
        container: qc.sec_seedy-asparagus-tzu
  QC.Sty:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS flake8:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-red-labradoodle.sh
        container: qc.sty_hazy-myrtle-corgi
      github.com/athenarc/EOSCF-ContentBasedRS hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-apricot-zebu.sh
        container: qc.sty_slimy-persimmon-urchin
  QC.Ver:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-apricot-kakapo.sh
        container: qc.ver_craggy-flax-squid
timeout: 5400
