config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/athenarc/EOSCF-ContentBasedRS:
      branch: master
      repo: https://github.com/athenarc/EOSCF-ContentBasedRS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-wisteria-lemming.sh
        container: qc.acc_randy-xanthic-barnacle
  QC.Doc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-turquoise-sloth.sh
        container: qc.doc_skimpy-scarlet-havanese
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-goldenrod-octopus.sh
        container: qc.doc_shabby-cyan-labradoodle
      github.com/athenarc/EOSCF-ContentBasedRS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-violet-gopher.sh
        container: qc.doc_queasy-aquamarine-saola
  QC.Lic:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-red-barracuda.sh
        container: qc.lic_snappy-lilac-dane
  QC.Sec:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-azure-ant.sh
        container: qc.sec_queasy-heliotrope-cow
  QC.Sty:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homely-olivine-zonkey.sh
        container: qc.sty_slimy-periwinkle-dingo
      github.com/athenarc/EOSCF-ContentBasedRS hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-grey-fowl.sh
        container: qc.sty_paltry-buff-ragdoll
  QC.Ver:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-indigo-armadillo.sh
        container: qc.ver_breezy-chartreuse-angora
timeout: 5400
