config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/athenarc/EOSCF-ContentBasedRS:
      branch: master
      repo: https://github.com/athenarc/EOSCF-ContentBasedRS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-bronze-chinook.sh
        container: qc.acc_flaky-vermilion-quetzal
  QC.Doc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-emerald-terrier.sh
        container: qc.doc_queasy-mauve-octopus
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-magnolia-quail.sh
        container: qc.doc_gummy-xanthic-chimpanzee
      github.com/athenarc/EOSCF-ContentBasedRS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-indigo-centipede.sh
        container: qc.doc_muzzy-pumpkin-wolverine
  QC.Lic:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-asparagus-okapi.sh
        container: qc.lic_randy-puce-drever
  QC.Sec:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-pink-woodpecker.sh
        container: qc.sec_blurry-denim-uguisu
  QC.Sty:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-bronze-baboon.sh
        container: qc.sty_slimy-turquoise-kingfisher
      github.com/athenarc/EOSCF-ContentBasedRS hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-gamboge-spaniel.sh
        container: qc.sty_skimpy-salmon-caracal
  QC.Ver:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-rose-scorpion.sh
        container: qc.ver_chewy-alizarin-civet
timeout: 5400
