config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/athenarc/EOSCF-ContentBasedRS:
      branch: master
      repo: https://github.com/athenarc/EOSCF-ContentBasedRS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-magnolia-mau.sh
        container: qc.acc_boozy-maroon-forest
  QC.Doc:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-sapphire-pig.sh
        container: qc.doc_wiggy-taupe-cockroach
      github.com/athenarc/EOSCF-ContentBasedRS git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-azure-donkey.sh
        container: qc.doc_sickly-cornflower-magpie
      github.com/athenarc/EOSCF-ContentBasedRS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-goldenrod-labradoodle.sh
        container: qc.doc_whiny-cream-magpie
  QC.Lic:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-denim-dogfish.sh
        container: qc.lic_lousy-lilac-peccary
  QC.Sec:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-gamboge-dachshund.sh
        container: qc.sec_snoopy-burgundy-bloodhound
  QC.Sty:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS flake8:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-wheat-octopus.sh
        container: qc.sty_cozy-taupe-cassowary
      github.com/athenarc/EOSCF-ContentBasedRS hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-cornflower-squirt.sh
        container: qc.sty_messy-wheat-eagle
  QC.Ver:
    repos:
      github.com/athenarc/EOSCF-ContentBasedRS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-ecru-scorpion.sh
        container: qc.ver_boozy-jade-gerbil
timeout: 5400
